language: node_js
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '0.12'
- 'iojs-v2'
- 'iojs-v3'
- '4'
sudo: 9000
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - graphicsmagick
    - imagemagick
before_install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- sudo bash curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-libvips.sh | sudo bash -
- sudo bash curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-ffmpeg.sh | sudo bash -
- sudo bash curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-imagemagick.sh | sudo bash -
- sudo bash curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-graphicsmagick.sh | sudo bash -
- sudo bash curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-flow.sh | sudo bash -
install:
- npm install
